---
title: "protein abundance_tidy"
author: "Stella Huang"
date: "9/27/2018"
output: html_document
---

```{r}
#load relevant libraries
library(tidyverse)

```



```{r}
# load in data
protein_id <- read.delim("protein_id.txt")
head(protein_id)
# select relevant columns
protein_id <- protein_id %>% select(c("Locus","sample","strain","treatment","day","Uniprot","NSAF"))

# convert to dataframe format
protein_id <- as.data.frame(protein_id)
#delete locus with "reverse"
protein_id <-protein_id[-grep("Reverse", protein_id$Locus),]
protein_id <- protein_id %>% select(-"Locus")
protein_id
```



```{r}
# spreads dataset along Uniprof
# row: sample
# columns: individual proteins
# matrix entries: NSAF
protein_id <- protein_id %>% select(c("sample","Uniprot","NSAF")) %>% spread("Uniprot","NSAF")

dim(protein_id)

#proportion of NA values:
sum(is.na(protein_id))/(dim(protein_id)[1]*dim(protein_id)[2])*100

write.csv(protein_id,file="protein_id.csv")
protein_id

```











two separate files: control & iso
proteins as rows and samples and col (transpose)
will show NSAF at diff time points

average the strains 
protein 1 at time1: will have 6 diff values
average the values

col: 7 time points
row: proteins
entires: average NSAF value from the 6 strains

day 0 for iso can be copied form control (bc they initially the same before treatment is effective)









